import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/layout/Sidebar";
import Navbar from "@/components/layout/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={geistSans.className}>
      <body
        className={`light antialiased h-screen flex flex-col`}
      >
        <div className="p-3 mx-auto flex flex-raw h-full">
          {/* Navbar */}
          <Navbar />
          {/* Sidebar */}
          <div className="w-[230px]">
            <Sidebar />
          </div>
          {/* Content */}
          <div className="h-full p-4.5 flex flex-col">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
